export type SkuType = "good" | "service";

export type SkuItem = {
  id: string;
  name: string;
  imageUrl: string | null;
  type: SkuType;
  hsnSac: string;
  unitPrice: number | null;
  costPrice: number | null;
  currency: string;
  description: string;
};

export const skuItemsSeed: SkuItem[] = [
  {
    id: "sku_001",
    name: "Website changes",
    imageUrl: null,
    type: "service",
    hsnSac: "1109",
    unitPrice: 100,
    costPrice: null,
    currency: "INR",
    description: "",
  },
  {
    id: "sku_002",
    name: "123",
    imageUrl: null,
    type: "good",
    hsnSac: "1321",
    unitPrice: 2,
    costPrice: null,
    currency: "INR",
    description: "",
  },
  {
    id: "sku_003",
    name: "Desktop",
    imageUrl: null,
    type: "good",
    hsnSac: "1212",
    unitPrice: 12,
    costPrice: null,
    currency: "USD",
    description: "",
  },
  {
    id: "sku_004",
    name: "HDMI",
    imageUrl: null,
    type: "good",
    hsnSac: "11",
    unitPrice: 11,
    costPrice: 8,
    currency: "NZD",
    description: "Cable",
  },
  {
    id: "sku_005",
    name: "USB type B",
    imageUrl: null,
    type: "good",
    hsnSac: "1007",
    unitPrice: 10,
    costPrice: 8,
    currency: "AUD",
    description: "Cable",
  },
  {
    id: "sku_006",
    name: "USB type A",
    imageUrl: null,
    type: "good",
    hsnSac: "1004",
    unitPrice: 10,
    costPrice: 8,
    currency: "USD",
    description: "Cable",
  },
  {
    id: "sku_007",
    name: "USB type C",
    imageUrl: null,
    type: "good",
    hsnSac: "1004",
    unitPrice: 8,
    costPrice: 4,
    currency: "USD",
    description: "Cable",
  },
  {
    id: "sku_008",
    name: "12 ft HDMI cable",
    imageUrl: null,
    type: "good",
    hsnSac: "1234",
    unitPrice: 40,
    costPrice: null,
    currency: "INR",
    description: "",
  },
  {
    id: "sku_009",
    name: "27\" computer monitor",
    imageUrl: null,
    type: "good",
    hsnSac: "1223",
    unitPrice: 30,
    costPrice: null,
    currency: "USD",
    description: "",
  },
  {
    id: "sku_010",
    name: "123er",
    imageUrl: null,
    type: "good",
    hsnSac: "123",
    unitPrice: 21,
    costPrice: null,
    currency: "INR",
    description: "",
  },
  {
    id: "sku_011",
    name: "Consulting hour",
    imageUrl: null,
    type: "service",
    hsnSac: "9983",
    unitPrice: 75,
    costPrice: null,
    currency: "USD",
    description: "1 hour of consulting",
  },
  {
    id: "sku_012",
    name: "Wireless mouse",
    imageUrl: null,
    type: "good",
    hsnSac: "8471",
    unitPrice: 15,
    costPrice: 9,
    currency: "AUD",
    description: "",
  },
  {
    id: "sku_013",
    name: "Laptop stand",
    imageUrl: null,
    type: "good",
    hsnSac: "8473",
    unitPrice: 25,
    costPrice: 14,
    currency: "NZD",
    description: "",
  },
  {
    id: "sku_014",
    name: "Onboarding session",
    imageUrl: null,
    type: "service",
    hsnSac: "9992",
    unitPrice: 200,
    costPrice: null,
    currency: "INR",
    description: "New client onboarding",
  },
  {
    id: "sku_015",
    name: "USB-C hub",
    imageUrl: null,
    type: "good",
    hsnSac: "8473",
    unitPrice: 22,
    costPrice: 13,
    currency: "USD",
    description: "7-in-1 adapter",
  },
];
